### ISSUE TITLE
Cannot Start Container "No deploy command found"

### ISSUE THREAD

**Issue by graboskyc** [QualiSystemsLab/docker-shell#2]
Running CloudShell 7.0EA

Steps to reproduce:
- Download latest release (Alpha 1)
- Edit zip file and put docker_deployment.py into dockerShell.zip\Resource Scripts (see issue 1)
- Import package
- Create new Docker Host
- Add Docker image/container of hello-world
- Deploy in new sandbox and see error "Deploy App ended with status Failed with error: No deploy command found"

The linux machine has the hello-world container already downloaded. Docker is running on port 4444. Linux machine has no firewall on. See screenshots.

![ss01](https://cloud.githubusercontent.com/assets/1686038/15191547/1a49a8e4-1783-11e6-89eb-3d611e1eaad0.PNG)
![ss02](https://cloud.githubusercontent.com/assets/1686038/15191548/1ce2f66e-1783-11e6-8acb-890ff2536cc9.PNG)
![ss03](https://cloud.githubusercontent.com/assets/1686038/15191550/1f3be5f6-1783-11e6-9a5c-04044a02a209.PNG)
![ss04](https://cloud.githubusercontent.com/assets/1686038/15191551/21d1a846-1783-11e6-8c03-8115f96f0e8a.PNG)
![ss05](https://cloud.githubusercontent.com/assets/1686038/15191554/2467ad8a-1783-11e6-80f5-6858b1a75c2f.PNG)

Also tried setting the Docker Host resource to the following permutations:
- IP:port
- http://ip:port
- moved port from 4444 to 4000 for docker in case something was hard-coded like in the tutorial 
- those permutations in address and "private ip" attribute and empty attribute

**Comment by doppleware** [comment]
I'll update the package, the deployment script must not get imported correctly.
Meanwhile you can just attach the script manually. 
Add the scripts/docker_deployment.py script to CloudShell and attach to the model of the docker deployment service. 

Make sure to add a 'name' parameter as seen below.

![image](https://cloud.githubusercontent.com/assets/93863/15368816/77fb0194-1d38-11e6-95d0-dbcf2c0c30e4.png)

Thanks,
Roni
